#!/usr/bin/env php

<?php
$doc = <<<'DOC'

Usage:
  img2text <imgfile> [--maxLen=<n>] [--fontSize=<n>] [--color] [--ansi] [--bgcolor=<#RRGGBB>]
  img2text (-h | --help)
Options:
  -h --help             show this screen.
  --ansi                output an ANSI rendering of the image
  --color               output a colored HTML rendering of the image.
  --fontSize=<n>        sets font size (in pixels) when outputting HTML,
                        default: 7
  --maxLen=<n>          resize image so that larger of width or height matches
                        maxLen, default: 100px
  --bgcolor=<#RRGGBB>   if specified, is blended with transparent pixels to
                        produce the output. In ansi case, if no bgcolor set, a
                        fully transparent pixel is not drawn at all, partially
                        transparent pixels drawn as if opaque
DOC;

require __DIR__.'/vendor/autoload.php';
$args = Docopt::handle($doc);
if ($args->args['<imgfile>']) {
    $options = [
        'ansi'     => $args->args['--ansi'],
        'color'    => $args->args['--color'],
        'fontSize' => $args->args['--fontSize'],
        'maxLen'   => $args->args['--maxLen'],
        'bgcolor'  => $args->args['--bgcolor'],
    ];

    $img = new Bigweb\Img2text\Img2text($args->args['<imgfile>'], $options);
    echo $img->render();
} else {
    foreach ($result as $k=>$v)
        echo $k.': '.json_encode($v).PHP_EOL;
}
